apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      nodeSelector:
        node-role: database
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://sensor:sensor@timescaledb:5432/sensor?sslmode=disable"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: sensor
  labels:
    app: postgres-exporter
    
spec:
  ports:
  - port: 9187
    targetPort: metrics
    name: metrics
  selector:
    app: postgres-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
    - sensor
  endpoints:
  - port: metrics
    interval: 30s