apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-server
  namespace: sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-server
  template:
    metadata:
      labels:
        app: sensor-server
    spec:
      containers:
      - name: sensor-server
        image: registry.crafthomelab.com/sensor-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: DB_TYPE
            value: postgresql
          - name: DB_NAME
            value: sensor
          - name: DB_USER
            value: sensor
          - name: DB_PASSWORD
            value: sensor
          - name: DB_HOST
            value: timescaledb
          - name: DB_PORT
            value: "5432"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10    
          periodSeconds: 10          
          timeoutSeconds: 3          # 추가: 요청 타임아웃
          failureThreshold: 3        # 추가: 실패 허용 횟수
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10    
          periodSeconds: 10          
          timeoutSeconds: 3          # 추가: 요청 타임아웃
          successThreshold: 1        # 추가: 성공으로 간주할 횟수
          failureThreshold: 3        # 추가: 실패 허용 횟수            
        resources:
          limits:
            cpu: 1000m
            memory: 1G
          requests:
            cpu: 1000m
            memory: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: sensor-server
  namespace: sensor
  labels:
    app: sensor-server
spec:
  selector:
    app: sensor-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sensor-server
  namespace: sensor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sensor-server
  namespaceSelector:
    matchNames:
      - sensor
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 14s